// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjcV3A0gepsVjurvB9Pj8lUeazLnji0R8',
    appId: '1:397679966147:web:2953ae5fe582261090ef76',
    messagingSenderId: '397679966147',
    projectId: 'vehiclerepairservice-c40ce',
    authDomain: 'vehiclerepairservice-c40ce.firebaseapp.com',
    storageBucket: 'vehiclerepairservice-c40ce.firebasestorage.app',
    measurementId: 'G-X8R8PLDV0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEzOyojrNvGcDUXgrkZs12RlFaZW70DY',
    appId: '1:397679966147:android:450181d54de94a0d90ef76',
    messagingSenderId: '397679966147',
    projectId: 'vehiclerepairservice-c40ce',
    storageBucket: 'vehiclerepairservice-c40ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivIal1znu4WgLeyYJfWfQ1ywSbrovjaU',
    appId: '1:397679966147:ios:2f8ecf23c993f10c90ef76',
    messagingSenderId: '397679966147',
    projectId: 'vehiclerepairservice-c40ce',
    storageBucket: 'vehiclerepairservice-c40ce.firebasestorage.app',
    iosClientId: '397679966147-d7a14lfignbu7p4j22uu4vvsva1glo9r.apps.googleusercontent.com',
    iosBundleId: 'com.brand.vehiclerepairservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCivIal1znu4WgLeyYJfWfQ1ywSbrovjaU',
    appId: '1:397679966147:ios:2082b5bd07719bd890ef76',
    messagingSenderId: '397679966147',
    projectId: 'vehiclerepairservice-c40ce',
    storageBucket: 'vehiclerepairservice-c40ce.firebasestorage.app',
    iosClientId: '397679966147-0tdktsedu43c2jb1g0hg0rm07tnrqpib.apps.googleusercontent.com',
    iosBundleId: 'com.brand.carWashService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjcV3A0gepsVjurvB9Pj8lUeazLnji0R8',
    appId: '1:397679966147:web:40e642d3b649b06290ef76',
    messagingSenderId: '397679966147',
    projectId: 'vehiclerepairservice-c40ce',
    authDomain: 'vehiclerepairservice-c40ce.firebaseapp.com',
    storageBucket: 'vehiclerepairservice-c40ce.firebasestorage.app',
    measurementId: 'G-KVTSQ2RPME',
  );

}