// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0CW1FOaAxytovqujq8_Tw7pV4b8bYYpw',
    appId: '1:383036743837:web:3f9a6093b32be445d97474',
    messagingSenderId: '383036743837',
    projectId: 'vehiclerepairservice-64661',
    authDomain: 'vehiclerepairservice-64661.firebaseapp.com',
    storageBucket: 'vehiclerepairservice-64661.firebasestorage.app',
    measurementId: 'G-RXPFR3ZDQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhntmcpOx695Lcgyzk6WEY5ISjSRMaT5Q',
    appId: '1:383036743837:android:d4a4ba7ec0c20ce7d97474',
    messagingSenderId: '383036743837',
    projectId: 'vehiclerepairservice-64661',
    storageBucket: 'vehiclerepairservice-64661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFoy39pS4u2zTpozDhRW69fDjHDlcQmhI',
    appId: '1:383036743837:ios:3cfff784ba7ee6a4d97474',
    messagingSenderId: '383036743837',
    projectId: 'vehiclerepairservice-64661',
    storageBucket: 'vehiclerepairservice-64661.firebasestorage.app',
    iosBundleId: 'com.brand.vehiclerepairservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFoy39pS4u2zTpozDhRW69fDjHDlcQmhI',
    appId: '1:383036743837:ios:3cfff784ba7ee6a4d97474',
    messagingSenderId: '383036743837',
    projectId: 'vehiclerepairservice-64661',
    storageBucket: 'vehiclerepairservice-64661.firebasestorage.app',
    iosBundleId: 'com.brand.vehiclerepairservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0CW1FOaAxytovqujq8_Tw7pV4b8bYYpw',
    appId: '1:383036743837:web:dc649a2809f1ea2ed97474',
    messagingSenderId: '383036743837',
    projectId: 'vehiclerepairservice-64661',
    authDomain: 'vehiclerepairservice-64661.firebaseapp.com',
    storageBucket: 'vehiclerepairservice-64661.firebasestorage.app',
    measurementId: 'G-KW6D56QHVZ',
  );

}